swagger: '2.0'
info:
  title: Big Commerce Theme Styles Oas 2 Yml API
  version: '1.0'
host: example.com
paths: {}
definitions:
  _context:
    type: object
    title: _context
    description: >-
      The combined context styles for all Stencil theme pages for quick
      reference. 
    properties:
      color:
        $ref: '#/definitions/color'
      font:
        $ref: '#/definitions/font'
      select:
        $ref: '#/definitions/select'
      checkbox:
        $ref: '#/definitions/checkbox'
      imageDimension:
        $ref: '#/definitions/imageDimension'
      text:
        $ref: '#/definitions/text'
      heading:
        $ref: '#/definitions/heading'
      reference:
        $ref: '#/definitions/reference'
  font:
    type: object
    title: font
    description: |-
      Used to select font value on theme setting

      Required fields: `type`, `label`, `id`, and `options`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: font
      label:
        type: string
        example: i18n.BodyTextFontFamily
      id:
        type: string
        example: body-font
      options:
        type: array
        items:
          type: object
          properties:
            group:
              type: string
              example: i18n.Karla
            label:
              type: string
              example: i18n.Karla
            value:
              type: string
              example: Google_Karla_400
    required:
      - type
      - label
      - id
      - options
  select:
    type: object
    properties: {}
    title: select
    description: |-
      Used to select custom value on theme settings. 

      Note: Option types should all be the same (i.e., string, number, etc.).
  checkbox:
    type: object
    title: checkbox
    description: |
      Used to toggle on theme settings (boolean value)

      Required fields: `type`, `label`, and `id`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: checkbox
      label:
        type: string
        example: i18n.HideBreadcrumbs
      force_reload:
        type: boolean
        example: true
      id:
        type: string
        example: hide_breadcrumbs
    required:
      - type
      - label
      - id
  imageDimension:
    type: object
    title: imageDimension
    description: >-
      Used to set image ratio on theme setting


      Required fields: `type`, `label`, `id`, and `options`.


      Note: "custom" value option will allow users to specify the width/height.
      Else, use values set by the theme developer.
    properties:
      type:
        type: string
        example: imageDimension
      id:
        type: string
        example: blog_size
      force_reload:
        type: boolean
        example: true
      label:
        type: string
        example: i18n.SizeOfImages
      options:
        type: array
        items:
          type: object
          properties:
            value:
              type: string
              example: 190x250
            label:
              type: string
              example: i18n.OptimizedForTheme
    required:
      - type
      - id
      - label
      - options
  text:
    type: object
    properties: {}
    title: text
    description: Used to set string value for theme settings
  heading:
    type: object
    title: heading
    description: 'Required fields: `type` and  `content`'
    properties:
      type:
        type: string
        example: heading
      content:
        type: string
        example: i18n.BackgroundAndLines
  reference:
    type: object
    properties: {}
    title: reference
    description: >-
      The reference field on a setting can show additional settings based on the
      value of another setting. For example, we may want to hide the `Product
      Sale Badge Label` setting if `Show product sale badges` setting equals
      none.
  color:
    type: object
    properties:
      type:
        type: string
        example: color
      label:
        type: string
        example: i18n.BannerBackground
      id:
        type: string
        example: color-primary
    required:
      - type
      - label
      - id
    description: |-
      Used to set color value on theme setting (hex value)

      Required fields: `type`, `label`, and  `id`
