swagger: '2.0'
info:
  title: Theme Styles
  version: '1.0'
host: example.com
paths: {}
definitions:
  _context:
    type: object
    title: _context
    description: >-
      The combined context styles for all Stencil theme pages for quick
      reference. 
    properties:
      color:
        $ref: '#/definitions/color'
      font:
        $ref: '#/definitions/font'
      select:
        $ref: '#/definitions/select'
      checkbox:
        $ref: '#/definitions/checkbox'
      imageDimension:
        $ref: '#/definitions/imageDimension'
      text:
        $ref: '#/definitions/text'
      heading:
        $ref: '#/definitions/reference-example2'
      reference:
        $ref: '#/definitions/reference'
  font:
    type: object
    title: font
    description: |-
      Used to select font value on theme setting

      Required fields: `type`, `label`, `id`, and `options`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: font
      label:
        type: string
        example: i18n.BodyTextFontFamily
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      id:
        type: string
        example: body-font
      options:
        type: array
        items:
          type: object
          properties:
            group:
              type: string
              example: i18n.Karla
            label:
              type: string
              example: i18n.Karla
            value:
              type: string
              example: Google_Karla_400
    required:
      - type
      - label
      - id
      - options
  select:
    type: object
    title: select
    description: |-
      Used to select custom value on theme settings. 

      Note: Option types should all be the same (i.e., string, number, etc.).

      Required fields: `type`, `label`, `id`, and `options`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: select
      label:
        type: string
        example: i18n.BodyTextFontSize
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      id:
        type: string
        example: fontSize-root
      options:
        type: array
        items:
          type: object
          properties:
            value:
              type: string
              example: 12
            label:
              type: string
              example: 12px
    required:
      - type
      - label
      - id
      - options
  checkbox:
    type: object
    title: checkbox
    description: |
      Used to toggle on theme settings (boolean value)

      Required fields: `type`, `label`, and `id`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: checkbox
      label:
        type: string
        example: i18n.HideBreadcrumbs
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      force_reload:
        type: boolean
        example: true
      id:
        type: string
        example: hide_breadcrumbs
    required:
      - type
      - label
      - id
  imageDimension:
    type: object
    title: imageDimension
    description: >-
      Used to set image ratio on theme setting


      Required fields: `type`, `label`, `id`, and `options`.


      Note: "custom" value option will allow users to specify the width/height.
      Else, use values set by the theme developer.
    properties:
      type:
        type: string
        example: imageDimension
      id:
        type: string
        example: blog_size
      force_reload:
        type: boolean
        example: true
      label:
        type: string
        example: i18n.SizeOfImages
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      options:
        type: array
        items:
          type: object
          properties:
            value:
              type: string
              example: 190x250
            label:
              type: string
              example: i18n.OptimizedForTheme
    required:
      - type
      - id
      - label
      - options
  text:
    type: object
    title: text
    description: |-
      Used to set string value for theme settings

      Required fields: `type`, `label`, and `id`.

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: text
      label:
        type: string
        example: i18n.ProductPriceLabelSale
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      force_reload:
        type: boolean
        example: true
      id:
        type: string
        example: pdp-sale-price-label
    required:
      - type
      - label
      - id
  heading:
    type: object
    title: heading
    description: 'Required fields: `type` and  `content`'
    properties:
      type:
        type: string
        example: heading
      content:
        type: string
        example: i18n.BackgroundAndLines
  reference:
    title: reference
    type: object
    properties:
      type:
        type: string
        example: select
      label:
        type: string
        example: i18n.ShowProductSaleBadges
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      id:
        type: string
        example: product_sale_badges
      force_reload:
        type: boolean
        example: true
      options:
        type: array
        items:
          type: object
          properties:
            value:
              type: string
              example: none
            label:
              type: string
              example: i18n.None
  color:
    type: object
    properties:
      type:
        type: string
        example: color
      label:
        type: string
        example: i18n.BannerBackground
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      id:
        type: string
        example: color-primary
    required:
      - type
      - label
      - id
    description: |-
      Used to set color value on theme setting (hex value)

      Required fields: `type`, `label`, and  `id`
  reference-example2:
    type: object
    title: ProductSaleBadgeLabel setting example
    properties:
      type:
        type: string
        example: text
      label:
        type: string
        example: i18n.ProductSaleBadgeLabel
        description: >-
          Title of the design option in theme styles UI. Supports the
          translation of regions that point to the correct localization from
          [schema_translation.json](https://developer.bigcommerce.com/stencil-docs/storefront-customization/directory-structure#schematranslationsjson).
      force_reload:
        type: boolean
        example: true
      id:
        type: string
        example: pdp_sale_badge_label
      reference:
        type: string
        example: product_sale_badges
      reference_default:
        type: string
        example: none
