swagger: '2.0'
info:
  title: Webhook Callbacks
  version: ''
  description: >-
    For a list of all webhook events see [Webhook
    Events](https://developer.bigcommerce.com/api-docs/getting-started/webhooks/webhook-events). 
host: '{$$.env.webhook_destination}?'
paths:
  /store/cart/created:
    post:
      responses:
        '200':
          $ref: '#/responses/CallbackResponse'
      description: >-
        This webhook will fire whenever a new cart is created either via a
        storefront shopper adding their first item to the cart or when a new
        cart being created via an API consumer. If it is from the storefront,
        then it fires when the first product is added to a new session.(The cart
        did not exist before) For the API it means a POST to /carts, (V3 and
        Storefront API). The store/cart/updated will also fire.
      security: []
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/putOrPostWebhook'
      tags:
        - Cart
      summary: /store/cart/created
      produces:
        - application/json
basePath: ''
schemes:
  - https
consumes: []
produces: []
tags:
  - name: Cart
securityDefinitions: {}
parameters:
  Accept:
    in: header
    type: string
    name: Accept
    default: application/json
  Content-Type:
    name: Content-Type
    in: header
    type: string
    default: application/json
definitions:
  callback_Base:
    type: object
    properties:
      scope:
        type: string
      store_id:
        type: string
      hash:
        type: string
      created_at:
        type: integer
      producer:
        type: string
      data: {}
  callbackData_Full:
    type: object
    properties: {}
responses:
  Webhooks Response:
    description: ''
    schema:
      type: object
      properties:
        id:
          type: integer
          description: Id of the webhook
          example: 18048287
        client_id:
          type: string
          description: 'Client ID, unique to the store'
          example: m9r6keqmo7h7f23btnpwernbez1kglkl
        store_hash:
          type: string
          description: 'Store permanent ID. '
          example: sftg45fsd
        scope:
          type: string
          description: Webhook event subscribed to
          example: store/order/*
        destination:
          type: string
          example: 'https://665b65a6.ngrok.io/webhooks'
          description: URL that returns a 200 response for webhooks
        headers:
          type: object
          description: >-
            You can pass in any number of custom headers to validate webhooks
            being returned.
          properties:
            custom:
              type: string
        is_active:
          type: boolean
          example: false
          description: If the webhook is active or not
        created_at:
          type: integer
          example: 1561488106
          description: Created time
        updated_at:
          type: integer
          example: 1561488106
          description: Updated time
    examples:
      application/json:
        id: 18048287
        client_id: m9r6keqmo7h7f23btnp3anbez1kglkl
        store_hash: '{store_hash}'
        scope: store/order/*
        destination: 'https://665b65a6.ngrok.io/webhooks'
        headers:
          username: Webhooks User
          password: Webhooks Password
        is_active: true
        created_at: 1561488106
        updated_at: 1561488106
  store/cart/created:
    description: >-
      This webhook will fire whenever a new cart is created either via a
      storefront shopper adding their first item to the cart or when a new cart
      being created via an API consumer. If it is from the storefront, then it
      fires when the first product is added to a new session.(The cart did not
      exist before) For the API it means a POST to /carts, (V3 and Storefront
      API). The store/cart/updated will also fire.
    schema:
      type: object
      properties:
        scope:
          type: string
        store_id:
          type: string
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
        hash:
          type: string
        created_at:
          type: integer
        producer:
          type: string
  CallbackResponse:
    description: >-
      To acknowledge that you received the webhook without issue, your server
      should return a 200 HTTP status code. Any other information you return in
      the request headers or request body will be ignored. Any response code
      outside the 200 range, including 3_xx_ codes, will indicate to us that you
      did not receive the webhook. When a webhook is not received (for whatever
      reason), we will retry the callback as described below.


      Need to set up a quick destination URL for testing? See [Tools for testing
      webhooks](https://developer.bigcommerce.com/api-docs/getting-started/webhooks/about-webhooks#about-webhooks_tools-for-debugging-and-testing-webhooks).
    schema:
      type: object
      properties: {}
