swagger: '2.0'
info:
  title: Big Commerce Webhook Events API
  version: '1.0'
host: example.com
paths: {}
responses:
  new-response:
    description: ''
    schema:
      type: object
      properties:
        scope:
          type: string
          example: store/order/created
          description: The event that triggered the webhook.
        store_id:
          type: string
          example: '1025646'
          description: The store ID
        data:
          type: object
          properties:
            type:
              type: string
              description: The entity that triggered the webhook
              example: order
            id:
              type: integer
        hash:
          type: string
        created_at:
          type: integer
        producer:
          type: string
