swagger: '2.0'
info:
  title: BigCommerce Common Models
  version: ''
  description: Models that are shared across BigCommerce APIs.
host: api.bigcommerce.com
paths:
  /example:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties: {}
definitions:
  _metaEmpty:
    type: object
    description: Used in responses for single objects
    title: _metaEmpty
  _pagination:
    type: object
    title: _pagination
    properties:
      total:
        description: Total number of items in the result set.
        type: integer
        format: int32
      count:
        description: Total number of items in the collection response.
        type: integer
        format: int32
      per_page:
        description: >-
          The amount of items returned in the collection per page, controlled by
          the limit parameter.
        type: integer
        format: int32
      current_page:
        description: The page you are currently on within the collection.
        type: integer
        format: int32
      total_pages:
        description: The total number of pages in the collection.
        type: integer
        format: int32
      links:
        $ref: '#/definitions/_links'
    description: In metaCollection
  _metaCollection:
    type: object
    title: _metaCollection
    properties:
      pagination:
        $ref: '#/definitions/_pagination'
    description: Used in responses that contains collections.
  _links:
    type: object
    description: >
      Links for the previous and next parts of the whole collection. In
      pagination.
    properties:
      previous:
        type: string
        description: |
          Link to the previous page returned in the response.
      current:
        type: string
        description: |
          Link to the current page returned in the response.
        example: '?page=1&limit=50'
      next:
        type: string
        description: |
          Link to the next page returned in the response.
    title: _links
  response_defaultError:
    allOf:
      - $ref: '#/definitions/_errorBase'
      - $ref: '#/definitions/_errorDetailed'
    title: response_defaultError
    description: Error message.
  _errorBase:
    type: object
    description: |
      Error payload for the BigCommerce API.
    properties:
      status:
        description: |
          The HTTP status code.
        type: integer
      title:
        description: |
          The error title describing the particular error.
        type: string
      type:
        type: string
      instance:
        type: string
    title: _errorBase
  response_404:
    description: Error payload for the BigCommerce API.
    type: object
    properties:
      status:
        description: |
          404 HTTP status code.
        type: integer
      title:
        description: The error title describing the particular error.
        type: string
      type:
        type: string
      instance:
        type: string
    title: response_404
  _errorDetailed:
    type: object
    properties:
      errors:
        type: object
        additionalProperties:
          type: string
        title: DetailedErrors
schemes:
  - https
parameters:
  Accept:
    in: header
    type: string
    name: Accept
    default: application/json
    required: true
  Content-Type:
    name: Content-Type
    in: header
    type: string
    default: application/json
    required: true
securityDefinitions:
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      Two types of API credentials are available to developers wishing to make
      requests against BigCommerce APIs:


      * [Store API
      Credentials](https://developer.bigcommerce.com/api-docs/getting-started/authentication#obtaining-store-api-credentials)
      (created in a store’s control panel)

      * [App API
      Credentials](https://developer.bigcommerce.com/api-docs/getting-started/building-apps-bigcommerce/building-apps)
      (created in the [Developer Portal](https://devtools.bigcommerce.com/))
  X-Auth-Token:
    type: apiKey
    in: header
    description: >-
      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication)
    name: X-Auth-Token
  OAuth:
    type: oauth2
    flow: application
    tokenUrl: 'https://login.bigcommerce.com/oauth2/token'
    description: >-
      ## Request Headers


      API requests are authenticated by the following HTTP headers:


      * `X-Auth-Client` -- The Client ID of the requesting app. 

      * `X-Auth-Token` -- Access token authorizing an app to access store data
      on behalf of a user.


      In addition, while not all resources require the Accept and Content-Type
      headers, many do. To ensure that your calls succeed, always include these
      headers. For more details on request headers and their accepted values,
      see [Request
      Headers](https://developer.bigcommerce.com/api-docs/getting-started/about-our-api#request-headers).


      `https://login.bigcommerce.com/oauth2/token`


      ### Request


      ```http

      POST /oauth2/token HTTP/1.1

      Host: login.bigcommerce.com

      Content-Type: application/x-www-form-urlencoded

      Content-Length: 186

      client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&code=qr6h3thvbvag2ffq&scope=store_v2_orders&grant_type=authorization_code&redirect_uri=https://app.example.com/oauth&context=stores/{STORE_HASH}

      ```


      ### Response


      ```json

      {
        "access_token": "ACCESS_TOKEN",
        "scope": "store_v2_orders",
        "user": {
          "id": 24654,
          "email": "merchant@mybigcommerce.com"
        },
        "context": "stores/STORE_HASH"
      }

      ```
security:
  - OAuth: []
