swagger: '2.0'
info:
  title: Big Commerce Theme Styles Oas 2 Yml API
  version: '1.0'
host: example.com
paths: {}
definitions:
  _context:
    type: object
    title: _context
    description: >-
      The combined context styles for all Stencil theme pages for quick
      reference. 
    properties:
      color:
        $ref: '#/definitions/color'
      font:
        $ref: '#/definitions/font'
      select:
        $ref: '#/definitions/select'
      checkbox:
        $ref: '#/definitions/checkbox'
      imageDimension:
        $ref: '#/definitions/imageDimension'
      text:
        $ref: '#/definitions/text'
      heading:
        $ref: '#/definitions/heading'
      reference:
        $ref: '#/definitions/reference'
  color:
    type: object
    properties: {}
    title: color
    description: Used to set color value on theme setting (hex value)
  font:
    type: object
    properties: {}
    title: font
    description: Used to select font value on theme setting
  select:
    type: object
    properties: {}
    title: select
    description: |-
      Used to select custom value on theme settings. 

      Note: Option types should all be the same (i.e., string, number, etc.).
  checkbox:
    type: object
    title: checkbox
    description: |
      Used to toggle on theme settings (boolean value)

      Required fields: `type`, `label`, and `id`

      Optional field: `force_reload`
    properties:
      type:
        type: string
        example: checkbox
      label:
        type: string
        example: i18n.HideBreadcrumbs
      force_reload:
        type: boolean
        example: true
      id:
        type: string
        example: hide_breadcrumbs
    required:
      - type
      - label
      - id
  imageDimension:
    type: object
    properties: {}
    title: imageDimension
    description: Used to set image ratio on theme setting
  text:
    type: object
    properties: {}
    title: text
    description: Used to set string value for theme settings
  heading:
    type: object
    properties: {}
    title: heading
  reference:
    type: object
    properties: {}
    title: reference
    description: >-
      The reference field on a setting can show additional settings based on the
      value of another setting. For example, we may want to hide the `Product
      Sale Badge Label` setting if `Show product sale badges` setting equals
      none.
