swagger: '2.0'
info:
  title: Big Commerce Theme Styles Oas 2 Yml API
  version: '1.0'
host: example.com
paths: {}
definitions:
  _context:
    type: object
    properties: {}
    title: _context
    description: >-
      The combined context styles for all Stencil theme pages for quick
      reference. 
