swagger: '2.0'
info:
  title: Big Commerce Theme Styles Oas 2 Yml API
  version: '1.0'
host: example.com
paths: {}
definitions:
  _context:
    type: object
    title: _context
    description: >-
      The combined context styles for all Stencil theme pages for quick
      reference. 
    properties:
      color:
        $ref: '#/definitions/color'
      font:
        $ref: '#/definitions/font'
      select:
        $ref: '#/definitions/select'
      checkbox:
        $ref: '#/definitions/checkbox'
      imageDimension:
        $ref: '#/definitions/imageDimension'
      text:
        $ref: '#/definitions/text'
  color:
    type: object
    properties: {}
    title: color
  font:
    type: object
    properties: {}
    title: font
  select:
    type: object
    properties: {}
    title: select
  checkbox:
    type: object
    properties: {}
    title: checkbox
  imageDimension:
    type: object
    properties: {}
    title: imageDimension
  text:
    type: object
    properties: {}
    title: text
