swagger: '2.0'
info:
  title: BigCommerce Common Models
  version: ''
  description: Models that are shared across BigCommerce APIs.
host: ''
paths: {}
definitions:
  _meta:
    type: object
    properties: {}
    title: _meta
