swagger: '2.0'
info:
  title: BigCommerce Common Models
  version: ''
  description: Models that are shared across BigCommerce APIs.
host: ''
paths: {}
definitions:
  _meta:
    type: object
    title: _meta
    properties:
      meta:
        type: object
        description: 'Data about the response, including pagination and collection totals.'
        title: Pagination
        properties:
          total:
            type: integer
            description: |
              Total number of items in the result set.
            example: 36
          count:
            type: integer
            description: |
              Total number of items in the collection response.
            example: 36
          per_page:
            type: integer
            description: >
              The amount of items returned in the collection per page,
              controlled by the limit parameter.
            example: 50
          current_page:
            type: integer
            description: |
              The page you are currently on within the collection.
            example: 1
          total_pages:
            type: integer
            description: |
              The total number of pages in the collection.
            example: 1
          links:
            type: object
            description: >
              Pagination links for the previous and next parts of the whole
              collection.
            properties:
              previous:
                type: string
                description: |
                  Link to the previous page returned in the response.
              current:
                type: string
                description: |
                  Link to the current page returned in the response.
                example: '?page=1&limit=50'
              next:
                type: string
                description: |
                  Link to the next page returned in the response.
  _metaEmpty:
    type: object
    description: Empty meta object; may be used later.
    title: _metaEmpty
