swagger: '2.0'
info:
  title: Storefront Form Fields
  description: Storefront API endpoints for retreiving form fields.
  version: v0.0.1
consumes:
  - application/json
produces:
  - application/json
paths:
  /form-fields:
    get:
      description: Returns an object with form fields groups.
      parameters:
        - name: filter
          in: query
          schema:
            type: string
            enum:
              - customerAccount
              - shippingAddress
              - billingAddress
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/FormFieldGroups'
          examples:
            application/json:
              customerAccount:
                - id: mollit nulla
                  name: non
                  custom: false
                  label: sint non laboris dolore ea
                  required: false
                  default: cillum aliquip qui occaecat ipsum
                  type: array
                  fieldType: dropdown
                  min: aute proident culpa magna fugiat
                  max: cillum commodo occaecat eiusmod veniam
                  maxLength: 76370587
                  secret: false
                  options:
                    helperLabel: Ut laboris
                    items:
                      value: sed amet qui non
                      label: exercitation Lorem elit incididunt
                    '': nulla
                - id: nulla commodo qui sint
                  name: in cupidatat e
                  custom: true
                  label: mollit culpa ad fugiat pariatur
                  required: false
                  default: cupidatat quis
                  type: date
                  fieldType: multiline
                  min: irure do commo
                  max: magna aute pariatur
                  maxLength: 66905400
                  secret: false
                  options:
                    helperLabel: eu
                    items:
                      value: laboris pariatur cupidatat aliquip culpa
                      label: occaecat commodo
                    '': irure anim et aliqua ea
                - id: sit consequat dolor exercitation
                  name: nulla dolor incididunt cupidatat culpa
                  custom: false
                  label: proident fugiat reprehenderit
                  required: true
                  default: velit culpa consequat ut ea
                  type: array
                  fieldType: radio
                  min: in
                  max: dolore adipisicing nisi
                  maxLength: 81860224
                  secret: false
                  options:
                    helperLabel: consequat proident consectetur laboris velit
                    items:
                      value: deserunt aliqua est esse tempor
                      label: irure sed aliquip
                    '': sunt eiusmod
              shippingAddress:
                - id: tempor
                  name: laboris
                  custom: true
                  label: eu vol
                  required: false
                  default: exercitation do
                  type: array
                  fieldType: radio
                  min: enim aliqui
                  max: 'no'
                  maxLength: 76115268
                  secret: false
                  options:
                    helperLabel: ea et
                    items:
                      value: esse
                      label: quis sed
                    '': dolor nisi quis proident
              billingAddress:
                - id: fugiat proident dolore ut dolor
                  name: cillum ex
                  custom: true
                  label: commodo incididunt aliquip minim
                  required: true
                  default: proident
                  type: array
                  fieldType: checkbox
                  min: enim nisi ad Excepteur
                  max: laboris non nulla
                  maxLength: 69985224
                  secret: false
                  options:
                    helperLabel: culpa commodo eu occaecat
                    items:
                      value: mollit nulla in qui adipisicing
                      label: aliquip aliqua
                    '': dolor
      tags:
        - Form Fields
definitions:
  FormFieldGroups:
    type: object
    description: Group of form field groups
    properties:
      customerAccount:
        $ref: '#/definitions/FormFields'
      shippingAddress:
        $ref: '#/definitions/FormFields'
      billingAddress:
        $ref: '#/definitions/FormFields'
  FormFields:
    type: array
    description: List of form fields for the group
    items:
      $ref: '#/definitions/FormField'
  FormField:
    type: object
    description: Form Field
    properties:
      id:
        type: string
        description: Field unique ID
      name:
        type: string
        description: Field name
      custom:
        type: boolean
        description: Wether is a custom field or system built-in field.
      label:
        type: string
        description: User-friendly label
      required:
        type: boolean
        description: Wether this field is required or not
      default:
        nullable: true
        type: string
        description: The field unique ID
      type:
        nullable: true
        type: string
        description: Type of the value hold by the field
        enum:
          - integer
          - string
          - array
          - date
      fieldType:
        nullable: true
        type: string
        description: Type of the field
        enum:
          - checkbox
          - text
          - date
          - multiline
          - radio
          - dropdown
      min:
        nullable: true
        type: string
        description: The minimun valid value for the field (integer and date type only)
      max:
        nullable: true
        type: string
        description: The minimun valid value for the field (integer and date type only)
      maxLength:
        nullable: true
        type: integer
        description: The maximum length for the value (string type only)
      secret:
        nullable: true
        type: boolean
        description: Whether the field represents a password field
      options:
        nullable: true
        type: object
        description: 'Extra data for radio, dropdown and checkbox field types.'
        properties:
          helperLabel:
            nullable: true
            type: string
            description: Placeholder text for dropdown field type.
          items:
            type: object
            description: List of possible values for this field.
            properties:
              value:
                type: string
                description: Field option value.
              label:
                type: string
                description: User friendly label.
          '':
            type: string
tags:
  - name: Form Fields
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
