info:
  version: 3.0.0
  title: Order Settings
  termsOfService: 'http://www.bigcommerce.com/terms'
  description: API endpoints for managing the Order settings of BigCommerce stores.
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
paths:
  /orders/settings:
    get:
      summary: Get Global order settings
      tags:
        - global settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GlobalOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
    put:
      summary: Update global order settings
      tags:
        - global settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalOrderSettings'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/GlobalOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '422':
          description: 'Order settings data is not valid. This is the result of missing required fields, or of invalid data. See the response for more details.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse422'
  /orders/settings/channel/{channel_id}:
    get:
      summary: Get order settings for a specific channel
      tags:
        - channel settings
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: path
          name: channel_id
          required: true
          description: 'Channel Id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ChannelOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
    put:
      summary: Update order settings for a specific channel
      tags:
        - channel settings
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: path
          name: channel_id
          required: true
          description: 'Channel Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelOrderSettings'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ChannelOrderSettings'
                  meta:
                    type: object
        '400':
          description: Bad request. Authentication Required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '422':
          description: 'Order settings data is not valid. This is the result of missing required fields, or of invalid data. See the response for more details.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse422'
components:
  schemas:
    GlobalOrderSettings:
      type: object
      properties:
        notifications:
          type: object
          description: Global notification settings.
          properties:
            order_placed:
              description: Global order notification settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses order notifications will be sent to. Empty array disables order notifications. Not nullable.
                  type: array
                  items:
                    type: string
            forward_invoice:
              description: Global order invoice forward settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses order invoices will be forwarded to. Empty array disables forwarding order invoices. Not nullable.
                  type: array
                  items:
                    type: string
      example:
        - notifications:
            email:
              addresses:
                - "admin@mystore.com"
                - "another-email@mystore.com"
    ChannelOrderSettings:
      type: object
      properties:
        notifications:
          type: object
          description: Channel notification settings.
          properties:
            order_placed:
              description: Channel order notification settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses channel order notifications will be sent to. If null will fall back to global value. Empty array disables order notifications for channel.
                  type: array
                  items:
                    type: string
            forward_invoice:
              description: Channel order invoice forward settings.
              type: object
              properties:
                email_addresses:
                  description: Email addresses channel order invoices will be forwarded to. If null will fall back to global value. Empty array disables forwarding order invoices for channel.
                  type: array
                  items:
                    type: string
      example:
        - notifications:
            email:
              addresses:
                - "admin@mystore.com"
    ErrorResponse400:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse404:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse422:
      type: object
      properties:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            errors:
              type: object
    BaseError:
      type: object
      description: |
        Error payload for the BigCommerce API.
      properties:
        status:
          description: |
            The HTTP status code.
          type: integer
        title:
          description: |
            The error title describing the particular error.
          type: string
        type:
          type: string
    DetailedErrors:
      type: object
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    description: Production API Gateway
    variables:
      store_hash:
        default: abc123
        description: Store hash used to identify the store.
openapi: 3.0.1