swagger: '2.0'
info:
  title: Storefront Subscriptions
  description: 'Endpoints for managing email subscriptions on the storefront. '
  version: v0.0.1
consumes:
  - application/json
produces:
  - application/json
paths:
  /subscriptions:
    post:
      description: >-
        Creates or updates an email subscriber.


        **Usage Notes:**

        * By default, customers receive abandoned cart emails as soon as they
        provide their email address in the checkout flow. They can opt out using
        this endpoint.

        * However, if **Store Settings > Miscellaneous > Require Consent** is
        enabled, Abandoned Cart Emails are not sent by default, and the customer
        should opt-in.
      parameters:
        - name: SubscriptionData
          in: body
          required: true
          schema:
            $ref: '#/definitions/SubscriptionRequest'
          x-examples:
            application/json:
              email: example@example.com
              acceptsMarketingNewsletter: false
              acceptsAbandonedCartEmails: false
      tags:
        - Subscription
      responses:
        '200':
          description: Returns a Subscriber Entity Object.
          schema:
            $ref: '#/definitions/Subscription'
        '404':
          description: Invalid payload provided
      summary: Create Email Subscription
      operationId: postStorefrontSubscriptions
definitions:
  SubscriptionRequest:
    type: object
    properties:
      email:
        type: string
        description: Email of subscriber
      acceptsMarketingNewsletter:
        type: boolean
        description: Has subscriber provided consent for receiving Marketing emails.
      acceptsAbandonedCartEmails:
        type: boolean
        description: Has subscriber provided consent for receiving Abandon Cart emails.
  Subscription:
    type: object
    description: Subscription properties.
    properties:
      id:
        type: integer
        description: |
          The unique numeric ID of the subscriber; increments sequentially.
      email:
        type: string
        description: |
          The email of the subscriber. Must be unique.
      firstName:
        type: string
        description: |
          The first name of the subscriber.
        minLength: 0
        maxLength: 255
      lastName:
        type: string
        description: |
          The last name of the subscriber.
        minLength: 0
        maxLength: 255
      source:
        type: string
        description: >
          The source of the subscriber. Values are: `storefront`, `order`, or
          `custom`.
        minLength: 0
        maxLength: 255
      orderId:
        type: integer
        description: |
          The ID of the source order, if source was an order.
        x-nullable: true
        minimum: 1
        maximum: 2147483647
      consents:
        type: array
        description: |
          The collection of consents the shopper is subscribing to.
